build:
    go build -o ./dist/ssg ./cmd/ssg/main.go

generate: build
    ./dist/ssg generate -d

serve: build
    ./dist/ssg serve

install: build
    sudo cp ./dist/ssg /usr/local/bin/ssg

clean:
    rm -rf ./dist/ssg ./public
        
