build:
    go build -o ./bin/ssg ./cmd/ssg/main.go

generate: build
    ./bin/ssg generate -d

serve: build
    ./bin/ssg serve

install: build
    sudo cp ./bin/ssg /usr/local/bin/ssg

clean:
    rm -rf ./bin/ssg ./public
        
